spring:

  ##MVC Config
  mvc:
    throw-exception-if-no-handler-found: 'true'
  resources:
    add-mappings: 'false'

  ##H2 Memory Bank
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  ##JPA Config
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true

  ##H2 Config
  h2:
    console:
      enabled: true
      path: /h2

  ##Exceptions Configs
  server:
    error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false